### ISSUE TITLE
Upgrade required

### ISSUE THREAD

**Issue by tristanlins** [terminal42/contao-NamespaceClassLoader#4]
The new composer class loader now comes with PSR-4 support. If the namespaceclassloader is installed in a composer driven contao installation, the autoloader fail because the shipped class loader is outdated.

see
https://github.com/composer/composer/blob/master/src/Composer/Autoload/ClassLoader.php#L139

**Comment by hamidabbaszadeh** [comment]
How to use for PSR-4?

**Comment by Toflar** [comment]
Not supported. The extension is useless for Contao 4 and adding PSR-4 support for 3.5 just makes no sense. Just go for Contao 4 only :)
