### ISSUE TITLE
contao 4 support

### ISSUE THREAD

**Issue by gebi84** [terminal42/contao-NamespaceClassLoader#7]
It would be great, if this works from the dependencys with contao 4 too. Many extensions depends on this extension and can not be installed by composer.

please update json to
`"contao/core-bundle": "~3.2 || ~4.1"`
`"contao-community-alliance/composer-plugin":"~2.4 || ~3.0",`

**Comment by aschempp** [comment]
`NamespaceClassLoader` should not be necessary with Contao 4, as the Composer autoloader is always available. The only problem is if an extension supports Contao 3.2, because 3.2 does not support optional dependencies…

What do you think @Toflar @qzminski

**Comment by Toflar** [comment]
We'll have to make it compatible with Contao 4 anyway. Otherwise you cannot install.

**Comment by qzminski** [comment]
Yup make it compatible with Contao 4 but drop support for 5 in the future.

**Comment by aschempp** [comment]
So we (@terminal42) discussed the topic and agreed that we should not update the extension.

If you're extension does support Contao 4 and composer, you should use the Composer autoloader to load the classes. This can easily accomplished by defining autoloading in your `composer.json` and make NamespaceClassLoader an optional dependency.

See https://github.com/isotope/core/commit/3f418a50ea81138834e72d9e978bbc196e63a9b2 for how I did that in Isotope. Feel free to ask if anything is unclear :-)

**Comment by aschempp** [comment]
I have updated the README with the necessary information: https://github.com/terminal42/contao-NamespaceClassLoader#upgrade-to-contao-4
