### ISSUE TITLE
Undefined constant self

### ISSUE THREAD

**Issue by ausi** [terminal42/contao-NamespaceClassLoader#8]
To fix `Use of undefined constant self - assumed 'self' in …\NamespaceClassLoader.php on line 86` the line https://github.com/terminal42/contao-NamespaceClassLoader/blob/708e615c326d68ffbb4970f317fe9f310e4ad049/NamespaceClassLoader.php#L86 should probably be replaced with:

```php
return array_map(array(__CLASS__, 'addContaoRoot'), $path);
```

**Comment by qzminski** [comment]
Fixed in 84ad023.

**Comment by ausi** [comment]
Thank you for the fix! 🎉

Is it possible to get version 1.0.3 pushed to the ER2 too?

**Comment by Toflar** [comment]
I'll take care.

**Comment by Toflar** [comment]
Done, sorry I missed that one. Let me know if it's not working :)
